# Generated by Django 5.0.4 on 2024-04-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'gallery'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name_plural': 'places'},
        ),
    ]
